<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4xfZXMv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4xfZXMv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4xfZXMv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4xfZXMv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4xfZXMv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4xfZXMv',
    'container.build_id' => 'a87edf0a',
    'container.build_time' => 1646065369,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4xfZXMv');
