<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2IFHwWP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2IFHwWP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2IFHwWP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2IFHwWP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2IFHwWP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2IFHwWP',
    'container.build_id' => '29ca9d6c',
    'container.build_time' => 1646487646,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2IFHwWP');
